"""
Palette tokenizer — builds model token streams from IndexedSprites and
reassembles generated values into sprites.

Sequence layout (see IMPLEMENTATION_NOTES.md for the full rationale):

  [BOS] [PAL]*n_palette [SEP] | mask phase | outline phase | interior phase

- Conditioning block: one PAL slot per palette color. The slot's COLOR is not
  a vocab id — it rides in per-token (r5, g5, b5) channel ids embedded by the
  conditioning encoder (CHANGE-032 palette grounding).
- Mask phase: every canvas position in raster order; value is TRANSPARENT_ID
  or OPQ_ID. This commits the silhouette first ("transparent pixels first").
- Outline phase: positions 4-adjacent to transparency/border, DERIVED from the
  committed mask (deterministic), raster order; values are palette indices.
- Interior phase: remaining visible positions, raster order; palette indices.

Every slot carries (value, x, y, phase). At slot t the model predicts the
value at position (x_t, y_t) — the position is a query, so generation is
well-posed even though the order is content-dependent (the content it depends
on — the mask — has already been generated by the time it is needed).
"""

from __future__ import annotations

import sys
from dataclasses import dataclass
from pathlib import Path

import numpy as np

_AM_PIXEL = Path(__file__).resolve().parent.parent.parent
if str(_AM_PIXEL) not in sys.path:
    sys.path.insert(0, str(_AM_PIXEL))

from model.architecture.config import (  # noqa: E402
    BOS_ID,
    OPQ_ID,
    PAL_ID,
    PHASE_COND,
    PHASE_INTERIOR,
    PHASE_MASK,
    PHASE_OUTLINE,
    SEP_ID,
    TRANSPARENT_ID,
)
from tools._common import IndexedSprite, outline_mask  # noqa: E402


@dataclass
class TokenizedSprite:
    values: np.ndarray  # int64 (L,) token ids
    xs: np.ndarray  # int64 (L,) canvas x (0 for conditioning slots)
    ys: np.ndarray  # int64 (L,)
    phases: np.ndarray  # int64 (L,) PHASE_*
    channels: np.ndarray  # int64 (L, 3) r5/g5/b5 per slot (0 except PAL slots)
    target_mask: np.ndarray  # bool (L,) True where the value is a prediction target
    width: int
    height: int
    palette: list[tuple[int, int, int]]


def tokenize(sprite: IndexedSprite) -> TokenizedSprite:
    h, w = sprite.grid.shape
    grid = sprite.grid
    outline = outline_mask(grid)

    values, xs, ys, phases, channels, tmask = [], [], [], [], [], []

    def emit(v, x, y, ph, ch=(0, 0, 0), target=True):
        values.append(v)
        xs.append(x)
        ys.append(y)
        phases.append(ph)
        channels.append(ch)
        tmask.append(target)

    emit(BOS_ID, 0, 0, PHASE_COND, target=False)
    for slot, (r, g, b) in enumerate(sprite.palette):
        emit(PAL_ID, 0, 0, PHASE_COND, (r >> 3, g >> 3, b >> 3), target=False)
    emit(SEP_ID, 0, 0, PHASE_COND, target=False)

    for y in range(h):  # mask phase — full canvas raster
        for x in range(w):
            emit(TRANSPARENT_ID if grid[y, x] == TRANSPARENT_ID else OPQ_ID, x, y, PHASE_MASK)

    for y in range(h):  # outline phase — mask-derived positions
        for x in range(w):
            if outline[y, x]:
                emit(int(grid[y, x]), x, y, PHASE_OUTLINE)

    for y in range(h):  # interior phase — remaining visible
        for x in range(w):
            if grid[y, x] != TRANSPARENT_ID and not outline[y, x]:
                emit(int(grid[y, x]), x, y, PHASE_INTERIOR)

    return TokenizedSprite(
        values=np.asarray(values, dtype=np.int64),
        xs=np.asarray(xs, dtype=np.int64),
        ys=np.asarray(ys, dtype=np.int64),
        phases=np.asarray(phases, dtype=np.int64),
        channels=np.asarray(channels, dtype=np.int64),
        target_mask=np.asarray(tmask, dtype=bool),
        width=w,
        height=h,
        palette=list(sprite.palette),
    )


def conditioning_length(n_palette: int) -> int:
    return n_palette + 2  # BOS + PAL slots + SEP


def assemble(
    mask_values: np.ndarray,  # (H*W,) TRANSPARENT_ID/OPQ_ID in raster order
    outline_positions: list[tuple[int, int]],
    outline_values: list[int],
    interior_positions: list[tuple[int, int]],
    interior_values: list[int],
    palette: list[tuple[int, int, int]],
    width: int,
    height: int,
) -> IndexedSprite:
    grid = np.zeros((height, width), dtype=np.int16)
    for (x, y), v in zip(outline_positions, outline_values):
        grid[y, x] = v
    for (x, y), v in zip(interior_positions, interior_values):
        grid[y, x] = v
    return IndexedSprite(palette=palette, grid=grid)


def mask_to_outline_interior(
    mask: np.ndarray,  # (H, W) bool visible
) -> tuple[list[tuple[int, int]], list[tuple[int, int]]]:
    """Derive the outline/interior position orders from a committed mask —
    the deterministic step between generation phases."""
    grid = mask.astype(np.int16)  # any nonzero index works for outline_mask
    outline = outline_mask(grid)
    outline_pos, interior_pos = [], []
    h, w = mask.shape
    for y in range(h):
        for x in range(w):
            if outline[y, x]:
                outline_pos.append((x, y))
            elif mask[y, x]:
                interior_pos.append((x, y))
    return outline_pos, interior_pos
